
ScreenManager:
    MainScreen:
        name: 'main'
    EditorScreen:
        name: 'editor'
    AboutScreen:
        name: "about"
    LicenseScreen:
        name: "license"   
    TermsScreen:
        name: "terms"    
    LicencePurchase:
        name: "licensepurchase"
    
        
<NoteRow>:
    orientation: 'vertical'
    size_hint_y: None
    height: dp(75)
    padding: [10, 8, 10, 8]
    spacing: dp(4)
    
    canvas.before:
        Color:
            rgba: root.bg_color
        Rectangle:
            pos: self.x, self.y + dp(4)
            size: self.width, self.height - dp(4)

    MDBoxLayout:
        spacing: 10
        MDLabel:
            text: root.note_title
            theme_text_color: "Custom"
            text_color: root.text_color
            size_hint_x: 0.7
            halign: 'left'
            valign: 'middle'
            on_touch_down:
                if self.collide_point(*args[1].pos): app.root.get_screen('main').open_note(root.note_id)

        MDLabel:
            text: root.last_updated
            theme_text_color: "Custom"
            text_color: root.hint_color
            size_hint_x: 0.3
            font_style: 'Caption'

        MDIconButton:
            icon: 'delete'
            theme_text_color: "Custom"
            text_color: root.icon_color
            size_hint_x: 0.1
            on_release: app.root.get_screen('main').delete_note(root.note_id)
    

<MainScreen>:
    FloatLayout:
        id: root_layout

        MDBoxLayout: #main
            id: main_controls 
            orientation: 'vertical'
            padding: dp(10)
            spacing: dp(10)

            MDTopAppBar:
                title: "Notes"
                elevation: 4
                left_action_items: [["plus", lambda x: root.new_note()]]
                right_action_items: [["sort", lambda x: root.sort_notes()],["cog", lambda x: root.show_settings()],["information", lambda x: root.show_about()]]       

            RecycleView:
                id: rv
                viewclass: 'NoteRow'
                RecycleBoxLayout:
                    default_size: None, dp(60)
                    default_size_hint: 1, None
                    size_hint_y: None
                    height: self.minimum_height
                    orientation: 'vertical'
    MDCard:
        id:settings_panel
        size_hint: .8, 1
        pos_hint: {'right': 1}
        elevation:10
        orientation: 'vertical'
        md_bg_color: app.theme_cls.bg_darkest
        opacity: 0.0
        disabled: True

        MDBoxLayout: #main
            orientation: 'vertical'
            padding: dp(20)
            spacing: dp(10)
            size_hint_y: 1
            height: self.minimum_height
                
            MDTopAppBar:
                title: "Settings"
                elevation: 2
                right_action_items: [["close", lambda x: root.hide_settings()]]
            
            MDLabel:
                text: "Theme"
                theme_text_color: "Primary"
                font_style: "Subtitle1"
                size_hint_y: None
                height: dp(30)

            MDRaisedButton:
                id: theme_button
                text: "Choose Theme"
                on_release: app.open_theme_menu(self)
            
            MDLabel:
                text: "License"
                theme_text_color: "Primary"
                font_style: "Subtitle1"
                size_hint_y: None
                height: dp(30)
            MDRaisedButton:
                text: "Open Licence Manager"
                on_release: root.open_license_manager()

            MDLabel:
                text: "Backup /Restore"
                theme_text_color: "Primary"
                font_style: "Subtitle1"
                size_hint_y: None
                height: dp(30)
            MDBoxLayout:
                size_hint_y: None
                height: dp(40)
                spacing: dp(10)
                MDRaisedButton:
                    text: "Backup"
                    on_release:root.prompt_backup(self)
                
                MDRaisedButton:
                    text: "Restore"
                    on_release:root.prompt_restore(self)
            Widget:
                size_hint_y: 1
            


<EditorScreen>:
    MDBoxLayout: #main
        orientation: 'vertical'
        padding: dp(10)
        spacing: dp(10)

        MDTopAppBar:
            title: root.last_updated  
            elevation: 4          
            height: dp(80)
            left_action_items:[["arrow-left", lambda x: root.open_main()]]
            right_action_items:[["undo", lambda x: root.undo()],["redo", lambda x: root.redo()]]

        MDTextField: #title
            id: title_input
            hint_text: "Title"            
            theme_text_color: "Custom"
            text_color_normal: 
                [0, 0, 0, 1] if app.theme_cls.theme_style == "Light" else [1, 1, 1, 1]
            text_color_focus: 
                [0, 0, 0, 1] if app.theme_cls.theme_style == "Light" else [1, 1, 1, 1]
            # hint_text_color: 
            #     [0.5, 0.5, 0.5, 1] if app.theme_cls.theme_style == "Light" else [0.7, 0.7, 0.7, 1]
            # cursor_color: 
            #     [0, 0, 0, 1] if app.theme_cls.theme_style == "Light" else [1, 1, 1, 1]
            # line_color_normal: 
            #     [0.88, 0.88, 0.88, 1] if app.theme_cls.theme_style == "Light" else [0.3, 0.3, 0.3, 1]
            # line_color_focus: 
            #     [0.2, 0.2, 0.2, 1] if app.theme_cls.theme_style == "Light" else [0.7, 0.7, 0.7, 1]
            mode: "rectangle"
            size_hint_y: None
            height: dp(50)
            on_text: root.save_note()

        MDTextField: #content
            id: content_input
            hint_text: "Notes"    
            theme_text_color: "Custom"
            text_color_normal: 
                [0, 0, 0, 1] if app.theme_cls.theme_style == "Light" else [1, 1, 1, 1]
            text_color_focus: 
                [0, 0, 0, 1] if app.theme_cls.theme_style == "Light" else [1, 1, 1, 1]
            # hint_text_color: 
            #     [0.5, 0.5, 0.5, 1] if app.theme_cls.theme_style == "Light" else [0.7, 0.7, 0.7, 1]
            # cursor_color: 
            #     [0, 0, 0, 1] if app.theme_cls.theme_style == "Light" else [1, 1, 1, 1]
            # line_color_normal: 
            #     [0.88, 0.88, 0.88, 1] if app.theme_cls.theme_style == "Light" else [0.3, 0.3, 0.3, 1]
            # line_color_focus: 
            #     [0.2, 0.2, 0.2, 1] if app.theme_cls.theme_style == "Light" else [0.7, 0.7, 0.7, 1]
            multiline: True
            mode: "rectangle"
            size_hint_y: 1
            on_text: root.save_note()
        
<AboutScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(20)

        MDTopAppBar:
            title: "About"
            elevation:4
            left_action_items:[["arrow-left",lambda x: root.go_back()]]

        ScrollView:
            MDLabel:
                id: about_label
                text: root.about_text
                theme_text_color: "Primary"
                font_style:"Body1"
                size_hint_y: None
                height: self.texture_size[1]
                padding: [10, 10]
            
<LicenseScreen>:
    MDBoxLayout: #main
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(10)
        MDTopAppBar:
            title: "Licensing"
            elevation:4
            left_action_items:[["arrow-left",lambda x: root.go_back()]]
        
        ScrollView:
            MDBoxLayout: #lic copy
                orientation: 'vertical'
                spacing: dp(10)
                padding: dp(10)
                size_hint_y: None
                height: self.minimum_height
                MDLabel: #basic lic info
                    text: "To access the full functionality of Notepad Calulator, Read and accept terms of service and purchase the licence below"
                    theme_text_color: "Primary"
                    font_style: "Body1"
                    text_size: self.width, None
                    size_hint_y: None
                    height: self.texture_size[1]
                    padding: [10,10]
                
                MDBoxLayout: # main terms
                    orientation: 'horizontal'
                    spacing: dp(10)
                    size_hint_y: None
                    height: dp(50)            
                    MDBoxLayout:  #terms
                        orientation: 'horizontal'
                        spacing: dp(10)
                        MDIconButton:
                            icon: "file-document-outline"                    
                            theme_text_color: "Primary"   
                            # theme_text_color: "Custom"
                            # text_color: .5,1,1,1
                            size_hint_y: None
                            height: dp(40)
                            on_release: root.open_screen('terms')
                        MDLabel:
                            text: "Read Terms"
                            theme_text_color: "Primary"                    
                            font_style: "Body1"
                            valign: "middle"

                    MDBoxLayout: #accept terms
                        orientation: 'horizontal'
                        spacing: dp(10)
                        MDCheckbox:
                            id: checkboxId
                            size_hint_y: None
                            height: dp(40)
                            theme_text_color: "Primary"
                        MDLabel:
                            text: "Accept Terms"
                            theme_text_color: "Primary"                    
                            font_style: "Body1"
                            valign: "middle"
                            # text_size: self.width, None
                            # size_hint_y: None
                            # height: self.texture_size[1]
                MDRaisedButton: #to licence butt
                    text: "Purchase license"
                    on_release: root.open_screen('licensepurchase')
                MDLabel:
                    text: "IF you have any query or would like to learn more about licensing, contanct us via"
                    theme_text_color: "Primary"
                    text_size: self.width, None
                    font_style:"Body1"
                    text_size: self.width, None
                    size_hint_y: None
                    height: self.texture_size[1]
                MDCard: #contact info
                    orientation: 'vertical'
                    padding: dp(10)
                    spacing: dp(10)
                    size_hint_y: None
                    height: self.minimum_height
                    elevation: 4
                    radius: [12]

                    MDLabel:
                        text: "Contact US"
                        font_style: "Subtitle1"
                        theme_text_color: "Primary"
                        text_size: self.width, None
                        size_hint_y: None
                        height: self.texture_size[1]
                    
                    MDSeparator:

                    MDBoxLayout: #email
                        orientation: 'horizontal'
                        spacing: dp(10)
                        adaptive_height:True
                        MDIconButton:
                            icon: "email-outline"
                            theme_text_color: "Custom"
                            text_color: 0, 0, 1, 1
                        MDLabel:
                            text: "email: ttk@gmail.com"
                            theme_text_color: "Custom"
                            text_color: 0,0,1,1
                            font_style:"Body1"     
                            text_size: self.width, None
                            size_hint_y: None
                            height: self.texture_size[1]
                    MDBoxLayout: #whatsapp
                        orientation: 'horizontal'
                        spacing: dp(10)
                        adaptive_height:True
                        MDIconButton:                   
                            icon: "whatsapp"
                            theme_text_color: "Custom"
                            text_color: 0, 0.7, 0, 1
                        MDLabel:
                            text: "whatsapp: +43435435353"
                            theme_text_color: "Custom"
                            text_color: 0,.7,0,1
                            font_style:"Body1"
                            text_size: self.width, None
                            size_hint_y: None
                            height: self.texture_size[1] 
         
<TermsScreen>:
    MDBoxLayout: #main
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(20)

        MDTopAppBar:
            title: "Terms and Conditions"
            elevation:4
            left_action_items:[["arrow-left",lambda x: root.go_back()]]

        ScrollView:
            MDLabel:
                id: terms_label
                text: root.terms_text
                theme_text_color: "Primary"
                font_style:"Body1"
                size_hint_y: None
                height: self.texture_size[1]
                padding: [10, 10]

<LicencePurchase>:
    MDBoxLayout: #main
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(10)

        MDTopAppBar:
            title: "Licence Activation"
            elevation:4
            left_action_items:[["arrow-left",lambda x: root.go_back()]]

        ScrollView:
            MDBoxLayout: #lic copy
                orientation: 'vertical'
                spacing: dp(10)
                padding: dp(10)
                size_hint_y: None
                height: self.minimum_height
                MDLabel:
                    text: "Copy and Share with support the App Id below"
                    theme_text_color: "Primary"
                    font_style: "Body1"
                    size_hint_y: None
                    height: self.texture_size[1]
                        
                MDLabel:
                    text: "App ID"
                    theme_text_color: "Primary"
                    font_style: "Subtitle1"
                    size_hint_y: None
                    height: self.texture_size[1]
                MDTextField:
                    id:  key_gen                
                    hint_text: "id"
                    text: root.app_id
                    readonly: True
                    multiline:True            
                    size_hint_y: None
                    height: dp(100) #self.texture_size[1]
                MDBoxLayout: #lic coppy button
                    orientation: 'horizontal'
                    spacing: dp(10)
                    size_hint_y: None
                    height: dp(50)
                    MDIconButton:  
                        icon: 'content-copy'
                        theme_text_color: "Custom"
                        text_color: (1, .5, 1, 1)  # optional: set your own color
                        size_hint: None,None
                        size: dp(40),dp(40)
                        pos_hint: {'top': 1.0}
                        on_release: root.copy_key_to_clipboard()       
                    MDLabel:
                        text: "Copy App Id"
                        theme_text_color: "Primary"
                        font_style: "Body1"     
                MDLabel:
                    text: "License Key"
                    theme_text_color: "Primary"
                    font_style: "Subtitle1"
                    size_hint_y: None
                    height: self.texture_size[1]
                MDTextField: #lic paste
                    id: license_text
                    hint_text: "License Key"
                    readonly: False
                    multiline:True            
                    size_hint_y: None
                    height: dp(100) #self.texture_size[1]
                MDBoxLayout: #lic submit
                    orientation: 'horizontal'
                    spacing: dp(10)
                    padding: dp(10)                    
                    size_hint_y: None
                    height: dp(60)
                    MDRaisedButton:
                        text: "Submit"                    
                        on_release: root.activate_app()                
                    MDRaisedButton:
                        text: "Cancel"                    
                        on_release: root.go_back()
                
                
                MDLabel: #contact
                    text: "Contact US"
                    font_style: "Subtitle1"
                    theme_text_color: "Primary"
                
                MDSeparator: #contact

                MDBoxLayout: #email
                    orientation: 'horizontal'
                    spacing: dp(10)
                    adaptive_height:True
                    MDIconButton:
                        icon: "email-outline"
                        theme_text_color: "Custom"
                        text_color: 0, 0, 1, 1
                    MDLabel:
                        text: "email: ttk@gmail.com"
                        theme_text_color: "Custom"
                        text_color: 0,0,1,1
                        font_style:"Body1"     
                        size_hint_y: None
                        height: self.texture_size[1]
                MDBoxLayout: #whatsapp
                    orientation: 'horizontal'
                    spacing: dp(10)
                    adaptive_height:True
                    MDIconButton:                    
                        icon: "whatsapp"
                        theme_text_color: "Custom"
                        text_color: 0, 0.7, 0, 1
                    MDLabel:
                        text: "whatsapp: +43435435353"
                        theme_text_color: "Custom"
                        text_color: 0,.7,0,1
                        font_style:"Body1"
                        size_hint_y: None
                        height: self.texture_size[1]  
                MDBoxLayout: #telegram
                    orientation: 'horizontal'
                    spacing: dp(10)
                    adaptive_height:True
                    MDIconButton:                    
                        icon: "telegram"
                        theme_text_color: "Custom"
                        text_color: .1, .7, .3, 1
                    MDLabel:
                        text: "telegram: @ttkhandle"
                        theme_text_color: "Custom"
                        text_color: 0,.7,0,1
                        font_style:"Body1"
                        size_hint_y: None
                        height: self.texture_size[1] 




